---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.custom.metrics.k8s.io
  labels:
    app: prometheus-adapter
spec:
  service:
    name: custom-metrics-prometheus-adapter
    namespace: monitoring
  group: custom.metrics.k8s.io
  version: v1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100